version: '3'
services:
  db:
    image: yobasystems/alpine-mariadb
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kambingberanakdalamkubur
    #deploy:
    #mode: replicated
    #replicas: 1
    networks:
      - local
    
  web:
    build: ./web
    image: uwsgi-nginx-flask-new
    volumes:
      - ./web/app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
      - STATIC_INDEX=1    
    # command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
    #deploy:
    #mode: replicated
    #replicas: 1
    networks:
      - local

networks: 
  local:

